name: Clean Commits
description: Fail a pipeline if commits include WIP or fixup!
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
        token: ${{ secrets.GH_API_TOKEN }}
    - shell: bash
      run: check-for-wip.sh
    - shell: bash
      run: check-for-fixup.sh
