name: Clean Commits
description: Fail a pipeline if commits include WIP or fixup!
runs:
  using: "composite"
  steps:
    - shell: bash
      run: check-for-wip.sh
    - shell: bash
      run: check-for-fixup.sh
