name: Clean Commits
description: Fail a pipeline if commits include WIP or fixup!
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - shell: bash
      run: ${{ github.action_path }}/check-for-wip.sh

    - shell: bash
      run: ${{ github.action_path }}/check-for-fixup.sh
